sudo: required
dist: trusty

language: c++

script:
 - mkdir build
 - cd build
 - cmake .. -DSKIP_SKIA=TRUE -DCMAKE_C_COMPILER=$C_COMPILER -DCMAKE_CXX_COMPILER=$CXX_COMPILER
 - make
 - ctest --output-on-failure

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - kalakris-cmake
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - g++-6
      env: C_COMPILER=gcc-6 CXX_COMPILER=g++-6
    - compiler: clang
      addons:
        apt:
          packages:
            - cmake
            - clang-3.9
            - libc++-dev
            - libc++abi-dev
          sources: &sources
            - kalakris-cmake
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise
            - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.9 main'
              key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
      env:
       - C_COMPILER=clang-3.9
       - CXX_COMPILER=clang++-3.9
