sudo: required
dist: trusty

language: c++

script:
 - mkdir build
 - cd build
 - cmake .. -DCMAKE_C_COMPILER=$C_COMPILER -DCMAKE_CXX_COMPILER=$CXX_COMPILER
 - make
 - make test

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env: C_COMPILER=gcc-6 CXX_COMPILER=g++-6
    - compiler: clang
      addons:
        apt:
          sources:
            - kalakris-cmake
            - llvm-toolchain-trusty-3.8
          packages:
            - cmake
            - clang-3.8
            - libc++-dev
            - libc++abi-dev
      env:
       - C_COMPILER=clang-3.8
       - CXX_COMPILER=clang++-3.8
