sudo: required
dist: trusty

language: c++

script:
 - wget https://cmake.org/files/v3.5/cmake-3.5.2-Linux-x86_64.tar.gz
 - tar -xf cmake-3.5.2-Linux-x86_64.tar.gz
 - mkdir build
 - cd build
 - ../cmake-3.5.2-Linux-x86_64/bin/cmake .. -DCMAKE_C_COMPILER=$C_COMPILER -DCMAKE_CXX_COMPILER=$CXX_COMPILER
 - make
 - ctest --output-on-failure

matrix:
  include:
    - compiler: GCC 6
      env:
        - C_COMPILER=gcc-6
        - CXX_COMPILER=g++-6
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - libgl1-mesa-dev
            - libegl1-mesa-dev
            - libgles2-mesa-dev
            - libxcb-util0-dev
    - compiler: GCC 7
      env:
        - C_COMPILER=gcc-7
        - CXX_COMPILER=g++-7
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - libgl1-mesa-dev
            - libegl1-mesa-dev
            - libgles2-mesa-dev
            - libxcb-util0-dev
    - compiler: clang-3.9
      env:
        - C_COMPILER=clang-3.9
        - CXX_COMPILER=clang++-3.9
      addons:
        apt:
          packages:
            - clang-3.9
            - libgl1-mesa-dev
            - libegl1-mesa-dev
            - libgles2-mesa-dev
            - libxcb-util0-dev
          sources:
            - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.9 main'
              key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
      before_install:
      - wget https://cmake.org/files/v3.5/cmake-3.5.2-Linux-x86_64.tar.gz
      - wget http://llvm.org/releases/3.9.1/llvm-3.9.1.src.tar.xz
      - wget http://llvm.org/releases/3.9.1/libcxxabi-3.9.1.src.tar.xz
      - wget http://llvm.org/releases/3.9.1/libcxx-3.9.1.src.tar.xz
      - tar -xf cmake-3.5.2-Linux-x86_64.tar.gz
      - export PATH=$PWD/cmake-3.5.2-Linux-x86_64/bin:$PATH
      - mkdir -p llvm/projects/libcxxabi llvm/projects/libcxx
      - tar --strip-components=1 -xf llvm-3.9.1.src.tar.xz -C llvm
      - tar --strip-components=1 -xf libcxxabi-3.9.1.src.tar.xz -C llvm/projects/libcxxabi
      - tar --strip-components=1 -xf libcxx-3.9.1.src.tar.xz -C llvm/projects/libcxx
      - mkdir llvm-build && cd llvm-build
      - cmake ../llvm -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang-3.9 -DCMAKE_CXX_COMPILER=clang++-3.9 -DCMAKE_INSTALL_PREFIX=/usr -DLIBCXX_INSTALL_EXPERIMENTAL_LIBRARY=TRUE -DLIBCXX_ENABLE_FILESYSTEM=TRUE
      - make cxx cxx_experimental
      - sudo make install-libcxxabi install-libcxx
      - cd ..
    - compiler: clang-4.0
      env:
        - C_COMPILER=clang-4.0
        - CXX_COMPILER=clang++-4.0
      addons:
        apt:
          packages:
            - clang-4.0
            - libgl1-mesa-dev
            - libegl1-mesa-dev
            - libgles2-mesa-dev
            - libxcb-util0-dev
          sources:
            - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-4.0 main'
              key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
      before_install:
        - wget https://cmake.org/files/v3.5/cmake-3.5.2-Linux-x86_64.tar.gz
        - wget http://llvm.org/releases/4.0.1/llvm-4.0.1.src.tar.xz
        - wget http://llvm.org/releases/4.0.1/libcxxabi-4.0.1.src.tar.xz
        - wget http://llvm.org/releases/4.0.1/libcxx-4.0.1.src.tar.xz
        - tar -xf cmake-3.5.2-Linux-x86_64.tar.gz
        - export PATH=$PWD/cmake-3.5.2-Linux-x86_64/bin:$PATH
        - mkdir -p llvm/projects/libcxxabi llvm/projects/libcxx
        - tar --strip-components=1 -xf llvm-4.0.1.src.tar.xz -C llvm
        - tar --strip-components=1 -xf libcxxabi-4.0.1.src.tar.xz -C llvm/projects/libcxxabi
        - tar --strip-components=1 -xf libcxx-4.0.1.src.tar.xz -C llvm/projects/libcxx
        - mkdir llvm-build && cd llvm-build
        - cmake ../llvm -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang-4.0 -DCMAKE_CXX_COMPILER=clang++-4.0 -DCMAKE_INSTALL_PREFIX=/usr -DLIBCXX_INSTALL_EXPERIMENTAL_LIBRARY=TRUE -DLIBCXX_ENABLE_FILESYSTEM=TRUE
        - make cxx cxx_experimental
        - sudo make install-libcxxabi install-libcxx
        - cd ..
