sudo: required
dist: trusty

language: c++

script:
 - mkdir build
 - cd build
 - cmake .. -G Ninja -DCMAKE_C_COMPILER=$C_COMPILER -DCMAKE_CXX_COMPILER=$CXX_COMPILER -DCMAKE_BUILD_TYPE=Release
 - ninja
 - ctest --output-on-failure

matrix:
  include:
    - os: linux
      compiler: gcc-7
      env:
        - C_COMPILER=gcc-7
        - CXX_COMPILER=g++-7
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - ninja
            - g++-7
            - libgl1-mesa-dev
            - libegl1-mesa-dev
            - libgles2-mesa-dev
            - libxcb-util0-dev
            - libxcb-image0-dev
      before_install:
        - . ./ci/setup_cmake.sh 3.8.2 Linux
        - . ./ci/setup_ninja.sh 1.8.2 linux
    - os: linux
      compiler: clang 4.0
      env:
        - C_COMPILER=clang-4.0
        - CXX_COMPILER=clang++-4.0
      addons:
        apt:
          packages:
            - ninja
            - clang-4.0
            - libgl1-mesa-dev
            - libegl1-mesa-dev
            - libgles2-mesa-dev
            - libxcb-util0-dev
            - libxcb-image0-dev
          sources:
            - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-4.0 main'
              key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
      before_install:
        - . ./ci/setup_cmake.sh 3.8.2 Linux
        - . ./ci/setup_ninja.sh 1.8.2 linux
        - . ./ci/setup_libcxx.sh 4.0.1
    - os: linux
      compiler: clang-5.0
      env:
        - C_COMPILER=clang-5.0
        - CXX_COMPILER=clang++-5.0
      addons:
        apt:
          packages:
            - ninja
            - clang-5.0
            - libgl1-mesa-dev
            - libegl1-mesa-dev
            - libgles2-mesa-dev
            - libxcb-util0-dev
            - libxcb-image0-dev
          sources:
            - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-5.0 main'
              key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
      before_install:
        - . ./ci/setup_cmake.sh 3.8.2 Linux
        - . ./ci/setup_ninja.sh 1.8.2 linux
        - . ./ci/setup_libcxx.sh 5.0.1
    - os: linux
      compiler: clang-6.0
      env:
        - C_COMPILER=clang-6.0
        - CXX_COMPILER=clang++-6.0
      addons:
        apt:
          packages:
            - ninja
            - clang-6.0
            - libgl1-mesa-dev
            - libegl1-mesa-dev
            - libgles2-mesa-dev
            - libxcb-util0-dev
            - libxcb-image0-dev
          sources:
            - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-6.0 main'
              key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
      before_install:
        - . ./ci/setup_cmake.sh 3.8.2 Linux
        - . ./ci/setup_ninja.sh 1.8.2 linux
        - . ./ci/setup_libcxx.sh 6.0.0
    - os: osx
      osx_image: xcode9.2
      env:
        - C_COMPILER=clang
        - CXX_COMPILER=clang++
      before_install:
        - . ./ci/setup_cmake.sh 3.8.2 Darwin
        - . ./ci/setup_ninja.sh 1.8.2 mac
        - . ./ci/setup_libcxx.sh 5.0.1
    - os: osx
      osx_image: xcode9.2
      env:
        - C_COMPILER=clang
        - CXX_COMPILER=clang++
      before_install:
        - . ./ci/setup_cmake.sh 3.8.2 Darwin
        - . ./ci/setup_ninja.sh 1.8.2 mac
        - . ./ci/setup_libcxx.sh 6.0.0
