environment:
  matrix:
  # MSVC
  - GENERATOR: Visual Studio 14 2015
    VCVARS: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat
    VCVARSARG: x86
  - GENERATOR: Visual Studio 14 2015 Win64
    VCVARS: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat
    VCVARSARG: amd64

  # Mingw-w64
  - GENERATOR: MinGW Makefiles
    PATH: C:\msys64\mingw64\bin;%PATH%
    PACMAN_PACKAGES: "mingw-w64-x86_64-boost"

  # Clang/C2
  #- GENERATOR: Visual Studio 14 2015 Win64
  #  VCVARS: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat
  #  VCVARSARG: amd64
  #  PATH: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\
  #  CMAKE_ARGS: -T"v140_clang_3_7"

  # Clang targeting MSVC
  #- GENERATOR: NMake Makefiles
  #  VCVARS: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat
  #  VCVARSARG: amd64
  #  CMAKE_ARGS: -DCMAKE_CXX_COMPILER="C:/Program Files/LLVM/msbuild-bin/cl.exe" -DCMAKE_CXX_FLAGS="-fms-compatibility-version=19" -DCMAKE_C_COMPILER="C:/Program Files/LLVM/msbuild-bin/cl.exe" -DCMAKE_C_FLAGS"-fms-compatibility-version=19"

  # Clang targeting mingw-w64
  - GENERATOR: MinGW Makefiles
    PATH: C:\msys64\mingw64\bin;%PATH%
    CMAKE_ARGS: -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang

configuration:
 - Debug
 - Release

shallow_clone: true

clone_script:
  - git clone -q --branch=%APPVEYOR_REPO_BRANCH% https://github.com/skui-org/skui.git %APPVEYOR_BUILD_FOLDER%
  - cd %APPVEYOR_BUILD_FOLDER%
  - git checkout -qf %APPVEYOR_REPO_COMMIT%
  - git submodule -q update --init --recursive

before_build:
  - mkdir build
  - cd build
  - if defined (VCVARS) call "%VCVARS%" %VCVARSARG%
  - if DEFINED PACMAN_PACKAGES C:\msys64\usr\bin\bash.exe -lc "pacman --needed --noconfirm -S %PACMAN_PACKAGES%"
  - set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
  - set PATH
  - cmake --version
  - cmake %CMAKE_ARGS% -G"%GENERATOR%" -DCMAKE_BUILD_TYPE="%CONFIGURATION%" .. || (echo CMAKEERROR && type CMakeFiles\CMakeError.log && echo CMAKEOUTPUT && type CMakeFiles\CMakeOutput.log && exit 1)

build_script:
  - cmake --build . --config %CONFIGURATION%

test_script:
  - ctest --output-on-failure -C %CONFIGURATION%
